"""This module defines data transfer objects (DTOs) for response."""

from typing import Optional
from pydantic import BaseModel, Field
from helpers.LlmEvents import LlmEvents

class StateResponse(BaseModel):
    """Response model for POST '/chat' endpoint
    
    This model represents the response payload for the chat endpoint, containing the request status, agent response, and a list of events generated in the agent.
    """
    status: Optional[int] = Field(
        default = 200,
        description = "HTTP status code of the response"
    )

    response: Optional[str] = Field(
        default = None,
        description = "The response message from the agent"
    )

    events: Optional[list[LlmEvents]] = Field(
        default = None,
        description = "List of events generated by the agent during processing"
    )
